### ISSUE TITLE
[BUG] Theme breaks on load but fixes after asset file update

### ISSUE THREAD

**Issue by Nadim147c** [Milkshiift/GoofCord#111]
- [x] I have searched and found no existing issues on the same topic
- [x] I have searched the [wiki](https://github.com/Milkshiift/GoofCord/wiki/FAQ) and found no mention of my problem

### Description
I'm currently applying a theme using Goofcord's asset loader. However, the theme breaks whenever Goofcord (re)starts. The theme works fine when I update the asset file, but after a new restart, the theme is broken again.

### Steps to Reproduce
1. Create `~/.config/goofcord/GoofCord/assets/wallpaper.css` and save the following theme
 <details>
<summary>Theme</summary>

```css
@import url('https://refact0r.github.io/midnight-discord/build/midnight.css');

[aria-label="Send a gift"],
[aria-label="Open GIF picker"],
[aria-label="Open sticker picker"]
{
    display: none;
}

:root {
	--font: 'figtree';
	--corner-text: 'Midnight';
    --online-indicator: #7b580c;     /* change to #23a55a for default green */
	--dnd-indicator: #ffb4ab;                  /* change to #f13f43 for default red */
	--idle-indicator: #364d2e;    /* change to #f0b232 for default yellow */
	--streaming-indicator: #422d00;       /* change to #593695 for default purple */
    --accent-1: #b3cea6;            /* links */
	--accent-2: #eec06d;             /* general unread/mention elements, some icons when active */
	--accent-3: #eec06d;             /* accent buttons */
	--accent-4: #3e382f;      /* accent buttons when hovered */
	--accent-5: #eec06d;   /* accent buttons when clicked */
	--mention:  #17130b;             /* mentions & mention messages */
	--mention-hover: #3e382f; /* mentions & mention messages when hovered */
	--text-0: #17130b;               /* text on colored elements */
	--text-1: #ece1d4;            /* other normally white text */
	--text-2: #ece1d4;            /* headings and important text */
	--text-3: #d1c5b4;    /* normal text */
	--text-4: #d1c5b4;    /* icon buttons and channels */
	--text-5: #9a8f80;               /* muted channels/chats and timestamps */
    --bg-1: #eec06d;                             /* dark buttons when clicked */
	--bg-2: #2f2921;              /* dark buttons */
	--bg-3: #201b13;               /* spacing, secondary elements */
	--bg-4: #17130b;                             /* main background color */
	--hover: #3e382f;                     /* channels and buttons when hovered */
	--active: #3e382f;                    /* channels and buttons when clicked or selected */
	--message-hover: #3e382f;             /* messages when hovered */
	--spacing: 12px;
	--list-item-transition: 0.2s ease;  /* channels/members/settings hover transition */
	--unread-bar-transition: 0.2s ease; /* unread bar moving into view transition */
	--moon-spin-transition: 0.4s ease;  /* moon icon spin */
	--icon-spin-transition: 1s ease;    /* round icon button spin (settings, emoji, etc.) */
	--roundness-xl: 22px; /* roundness of big panel outer corners */
	--roundness-l: 20px; /* popout panels */
	--roundness-m: 16px; /* smaller panels, images, embeds */
	--roundness-s: 12px; /* members, settings inputs */
	--roundness-xs: 10px; /* channels, buttons */
	--roundness-xxs: 8px; /* searchbar, small elements */
	--discord-icon: none; /* discord icon */
	--moon-icon: block; /* moon icon */
	--moon-icon-url: url('https://upload.wikimedia.org/wikipedia/commons/c/c4/Font_Awesome_5_solid_moon.svg'); /* custom icon url */
	--moon-icon-size: auto;
	--login-bg-filter: saturate(0.3) hue-rotate(-15deg) brightness(0.4); /* login background artwork */
	--green-to-accent-3-filter: hue-rotate(56deg) saturate(1.43); /* add friend page explore icon */
	--blurple-to-accent-3-filter: hue-rotate(304deg) saturate(0.84) brightness(1.2); /* add friend page school icon */
}
.selected_f5eb4b,
.selected_f6f816 .link_d8bfb3 {
  color: var(--text-0) !important;
  background: var(--accent-3) !important;
}

.selected_f6f816 .link_d8bfb3 * {
  color: var(--text-0) !important;
  fill: var(--text-0) !important;
}
```
 </details>

 2. Restart goofcord

### Screenshots
> Note: Ignore the color. It's just newly generated color.

| At startup | After Reload |
| -------------- | --------------- |
| ![Image](https://github.com/user-attachments/assets/118c2e4e-b2cf-4442-a283-a89fec4056f0) | ![Image](https://github.com/user-attachments/assets/cb828617-8b26-4205-ac23-e7aab2baca04) |

### Environment
- Operating System: Arch Linux
- GoofCord Version: 1.9.0
- Way of installing: AUR

### Additional Information
I'm guessing the asset's css is injected before Discord's css. Thus, Discord's css overwriting the theme css. I'm not sure!
